ARG BASE_IMAGE=osrf/ros
ARG BASE_TAG=humble-desktop-full

FROM ${BASE_IMAGE}:${BASE_TAG}

# set the environment variable with the command ENV <key>=<value>, it can be replaced online
ENV DEBIAN_FRONTEND=noninteractive
ENV GZ_VERSION=fortress
## arg ros2 distro
ARG DISTRO=humble
# RUN is used to execute and add new layer on top of the base immage
RUN apt-get update && apt-get install -y \
    ros-humble-plotjuggler \
    ros-humble-ros-gz \
    ros-humble-joint-state-publisher \
    ros-humble-joint-state-publisher-gui \
    ros-humble-ign-ros2-control \
    ros-humble-teleop-twist-joy \
    ros-humble-joy \
    ros-humble-pinocchio \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-xacro \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-plotjuggler-ros \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-rviz2 \
    pipx \
    chrony \
    tmux python3-pip \
    xterm \
    libeigen3-dev \
    nano \
    nautilus \
    iputils-ping \
    iproute2 \
    python3-rosdep \
    sudo git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG MYUID=1000
ARG MYGID=1000
ARG USER=ros
ARG PWDR=/

RUN OLD_USER=$(awk -v uid="$MYUID" -F ':' '$3==uid {print $1}' /etc/passwd) \
    && if [ -z "${OLD_USER}" ]; then \
        # There is no existing UID equal to MYUID.
        # Create the same user as the host itself. (By default Docker creates the container as root, which is not recommended.)
        addgroup --gid ${MYGID} ${USER} \
        && adduser --gecos "ROS User" --disabled-password --uid ${MYUID} --gid ${MYGID} ${USER} \
        && usermod -a -G dialout ${USER} \
        && echo ${USER}" ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/99_aptget \
        && chmod 0440 /etc/sudoers.d/99_aptget && chown root:root /etc/sudoers.d/99_aptget ; \
    else \
        usermod -l ${USER} ${OLD_USER} \
        && sudo usermod -d /home/${USER} -m ${USER} \
        && echo ${USER}" ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/99_aptget \
        && chmod 0440 /etc/sudoers.d/99_aptget && chown root:root /etc/sudoers.d/99_aptget ; \
    fi

# Choose to run as user
ENV USER=${USER}
USER ${USER}

# Change HOME environment variable
ENV HOME=/home/${USER}

# Set up workspace
ARG WORKSPACE=docker_navigation
WORKDIR /home/${USER}/${WORKSPACE}

# Install python packages as user
RUN pip3 install --user numpy

# Set up environment
COPY ./docker/.config/update_bashrc_ros_2 /sbin/update_bashrc_ros_2

RUN sudo chmod +x /sbin/update_bashrc_ros_2 ; sudo chown ${USER} /sbin/update_bashrc_ros_2 \
 && echo 'echo "source '${PWDR}'/install/setup.bash" >> ~/.bashrc' >> /sbin/update_bashrc_ros_2 \
 && cat /sbin/update_bashrc_ros_2 \
 && sync ; /bin/bash -c /sbin/update_bashrc_ros_2 ; sudo rm /sbin/update_bashrc_ros_2

# Change entrypoint to source ~/.bashrc and start in ~
COPY ./docker/.config/entrypoint.sh /ros_entrypoint.sh
RUN sudo chmod +x /ros_entrypoint.sh ; sudo chown ${USER} /ros_entrypoint.sh \
 && echo "cd "${PWDR} >> /ros_entrypoint.sh \
 && echo 'exec bash -i -c $@' >> /ros_entrypoint.sh \
 && cat /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]